// Generated by CoffeeScript 1.6.3
(function() {
  var fd, fs, mkdirp;

  fd = require('path');

  fs = require('fs');

  mkdirp = module.exports = function(path, mode) {
    var err;
    if (mode == null) {
      mode = 0x1fd;
    }
    path = fd.resolve(path);
    if (!fs.existsSync(path)) {
      try {
        return fs.mkdirSync(path, mode);
      } catch (_error) {
        err = _error;
        mkdirp(fd.dirname(path), mode);
        return fs.mkdirSync(path, mode);
      }
    }
  };

}).call(this);
